name: Fineract CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-core:
    uses: ./.github/workflows/build-core.yml
    secrets: inherit

  build-embeddable-progressive-loan-jar:
    uses: ./.github/workflows/build-progressive-loan.yml
    secrets: inherit

  build-docker-image:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit

  build-documentation:
    uses: ./.github/workflows/build-documentation.yml
    secrets: inherit

  run-quality-checks:
    uses: ./.github/workflows/build-quality-checks.yml
    secrets: inherit

  run-cucumber-tests:
    uses: ./.github/workflows/build-cucumber.yml
    secrets: inherit

  run-integrations-tests-on-postgresql:
    uses: ./.github/workflows/build-postgresql.yml
    secrets: inherit

  run-integrations-tests-on-mysql:
    uses: ./.github/workflows/build-mysql.yml
    secrets: inherit

  run-integrations-tests-on-mariadb:
    uses: ./.github/workflows/build-mariadb.yml
    secrets: inherit

  run-e2e-tests:
    uses: ./.github/workflows/build-e2e-tests.yml
    secrets: inherit

  run-liquibase-only-on-postgresql:
    uses: ./.github/workflows/liquibase-only-postgresql.yml
    secrets: inherit

  run-messaging-smoke-tests:
    uses: ./.github/workflows/smoke-messaging.yml
    secrets: inherit

  run-api-backward-compatibility:
    uses: ./.github/workflows/verify-api-backward-compatibility.yml
    secrets: inherit

  run-liquibase-backward-compatibility:
    uses: ./.github/workflows/verify-liquibase-backward-compatibility.yml
    secrets: inherit

  run-liquibase-ddl-safety:
    uses: ./.github/workflows/verify-liquibase-ddl-safety.yml
    secrets: inherit

  run-regression-safety-db-changes:
    uses: ./.github/workflows/regression-safety-db-changes.yml
    secrets: inherit

  run-sonarqube:
    uses: ./.github/workflows/sonarqube.yml
    secrets: inherit

  run-integration-tests-sequentially-on-postgresql:
    uses: ./.github/workflows/run-integration-test-sequentially-postgresql.yml
    secrets: inherit

  publish-dockerhub:
    uses: ./.github/workflows/publish-dockerhub.yml
    secrets: inherit
